---
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# waterpumpkwale

<!-- badges: start -->

<!-- badges: end -->

## Installation

You can install the development version of waterpumpkwale from
[GitHub](https://github.com/waterpumpkwale) with:

``` r
# install.packages("devtools")
devtools::install_github("openwashdata/waterpumpkwale")
```

## Introduction

This dataset contains a summary of the weekly volumetric output of pumps
monitored using Smart Handpump sensors for 2014 and 2015.[^1][^2]

[^1]: Grants that permitted the data collection include: Groundwater
    Risk Management for Growth and Development project (NE/M008894/1)
    funded by NERC/ESRC/DFID's UPGro programme; New mobile citizens and
    waterpoint sustainability in rural Africa (ES/J018120/1) ESRC-DFID;
    Groundwater Risks and Institutional Responses for Poverty Reduction
    in Rural Africa (NE/L001950/1) funded by NERC/ESRC/DFID's UPGro
    programme.
[^2]: More information of the data sources: https://webapps.bgs.ac.uk/services/ngdc/accessions/index.html?simpleText=upgro

Notes:

1.  The accuracy of these volume figures should be considered to be +/-
    20%.
2.  The dataset has gaps due to variable signal, and some attrition due
    to damage and vandalism.
3.  Not all pumps in the study area were under monitoring.

### References

[1] P. Thomson, R. Hope, and T. Foster, "GSM-enabled remote monitoring
of rural handpumps: a proof-of-concept study," Journal of
Hydroinformatics, vol. 14, no. 4, pp. 829--839, 05 2012. [Online].
Available: <https://doi.org/10.2166/hydro.2012.183>

[2] Behar, J., Guazzi, A., Jorge, J., Laranjeira, S., Maraci, M.A.,
Papastylianou, T., Thomson, P., Clifford, G.D. and Hope, R.A., 2013.
Software architecture to monitor handpump performance in rural Kenya. In
Proceedings of the 12th International Conference on Social Implications
of Computers in Developing Countries, Ochos Rios, Jamaica. pp. 978 (Vol.
991).

## Example 

## Citation 
